apiVersion: v1
kind: Pod
metadata:
  name: minotaur
spec:
  hostNetwork: true
  hostPID: true
  initContainers:
    - name: init
      image: daemon1024/minotaur-init
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /tmp/minotaur
          name: dump
        - mountPath: /lib/modules
          name: lib-modules-path
          readOnly: true
        - mountPath: /sys/fs/bpf
          name: sys-fs-bpf-path
        - mountPath: /sys/kernel/security
          name: sys-kernel-security-path
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug-path
        - mountPath: /media/root/etc/os-release
          name: os-release-path
          readOnly: true
        - mountPath: /usr/src
          name: usr-src-path
          readOnly: true
  containers:
    - name: main
      image: daemon1024/minotaur
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /tmp/minotaur
          name: dump
        - mountPath: /sys/fs/bpf
          name: sys-fs-bpf-path
        - mountPath: /sys/kernel/security
          name: sys-kernel-security-path
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug-path
        - mountPath: /media/root/etc/os-release
          name: os-release-path
          readOnly: true
  volumes:
    - emptyDir: {}
      name: dump
    - hostPath:
        path: /lib/modules
        type: Directory
      name: lib-modules-path
    - hostPath:
        path: /sys/fs/bpf
        type: Directory
      name: sys-fs-bpf-path
    - hostPath:
        path: /sys/kernel/security
        type: Directory
      name: sys-kernel-security-path
    - hostPath:
        path: /sys/kernel/debug
        type: Directory
      name: sys-kernel-debug-path
    - hostPath:
        path: /etc/os-release
        type: File
      name: os-release-path
    - hostPath:
        path: /usr/src
        type: Directory
      name: usr-src-path
